import { ytTimeToSeconds } from '../helpers';

const initialPlaylist = {
  total: 20,
  items: [
    {
      videoId: 'OE2qEpkWWoQ',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/OE2qEpkWWoQ/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/OE2qEpkWWoQ/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Run Away With Me (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 252,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: '_-XWAQ1wCAA',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/_-XWAQ1wCAA/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/_-XWAQ1wCAA/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Emotion (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015 Buy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 198,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: '77PzXCKDyVQ',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/77PzXCKDyVQ/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/77PzXCKDyVQ/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - I Really Like You (Audio)',
      description:
        'Get E•MO•TION on iTunes now: http://smarturl.it/E-MO-TION\n\nSign up for Carly Rae Jepsen news here: http://smarturl.it/CRJ.News\n\nMusic video by Carly Rae Jepsen performing I Really Like You. (C) 2015 School Boy/Interscope Records',
      duration: 205,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      projection: 'rectangular'
    },
    {
      videoId: 'OKsAnpPg15c',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/OKsAnpPg15c/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/OKsAnpPg15c/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Gimmie Love (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015 Buy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 202,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'W374tWnsk70',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/W374tWnsk70/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/W374tWnsk70/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - All That (Audio)',
      description:
        'Get E•MO•TION on iTunes now: http://smarturl.it/E-MO-TION\n\nSign up for Carly Rae Jepsen news here: http://smarturl.it/CRJ.News',
      duration: 276,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      projection: 'rectangular'
    },
    {
      videoId: 'YSf_i1SUFhM',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/YSf_i1SUFhM/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/YSf_i1SUFhM/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Boy Problems (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 223,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'gBOhnT6bUaY',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/gBOhnT6bUaY/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/gBOhnT6bUaY/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Making The Most Of The Night (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 239,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: '_98VZT9s7M0',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/_98VZT9s7M0/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/_98VZT9s7M0/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Your Type (Audio)',
      description:
        'Get E•MO•TION on iTunes now: http://smarturl.it/E-MO-TION\n\nArt by Kelsey Montague\nInstagram: https://instagram.com/kelseymontagueart/\nFacebook: https://www.facebook.com/pages/Kelsey-Montague-Art/379278752084914\nTwitter: https://twitter.com/kelsmontagueart\nWebsite: http://kelseymontagueart.com/\n\nConnect with Carly Rae Jepsen:\nOfficial - http://www.carlyraemusic.com \nYouTube: https://www.youtube.com/user/CarlyRaeMusic \nTwitter - https://twitter.com/CarlyRaeJepsen \nFacebook - https://www.facebook.com/CarlyRaeJepsen \nInstagram - http://instagram.com/CarlyRaeJepsen \nSign up for Carly Rae Jepsen news here: http://smarturl.it/CRJ.News\n\nhttp://vevo.ly/ac4m7w',
      duration: 198,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      projection: 'rectangular'
    },
    {
      videoId: 'S2BGjJ_4BTk',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/S2BGjJ_4BTk/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/S2BGjJ_4BTk/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: "Carly Rae Jepsen - Let's Get Lost (Audio)",
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 194,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'RPrZUiDVHrM',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/RPrZUiDVHrM/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/RPrZUiDVHrM/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - LA Hallucinations (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 185,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'iBPw0l26L58',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/iBPw0l26L58/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/iBPw0l26L58/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Warm Blood (Audio)',
      description:
        'Get E•MO•TION on iTunes now: http://smarturl.it/E-MO-TION\n\nArt by Shelby Edwards of LITTLEDRILL\nInstagram: http://instagram.com/LITTLEDRILL\nTwitter: http://twitter.com/itsLITTLEDRILL\nTumblr: http://LITTLEDRILL.tumblr.com\n\nConnect with Carly Rae Jepsen:\nOfficial - http://www.carlyraemusic.com\nYouTube: http://www.youtube.com/carlyraejepsen...\nTwitter - https://twitter.com/CarlyRaeJepsen\nFacebook - https://www.facebook.com/CarlyRaeJepsen\nInstagram - http://instagram.com/CarlyRaeJepsen\n\n“Warm Blood” was produced by Rostam Batmanglij.\n\nSign up for Carly Rae Jepsen news here: http://smarturl.it/CRJ.News\n\nhttp://vevo.ly/vqKKkx',
      duration: 254,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: true,
      projection: 'rectangular'
    },
    {
      videoId: 'FLkj9zr0-sQ',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/FLkj9zr0-sQ/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/FLkj9zr0-sQ/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - When I Needed You (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 222,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'a79Y7Mbqx1I',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/a79Y7Mbqx1I/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/a79Y7Mbqx1I/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Black Heart (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 177,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: '6_zD5-ij7So',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/6_zD5-ij7So/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/6_zD5-ij7So/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: "Carly Rae Jepsen - I Didn't Just Come Here To Dance (Audio)",
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 220,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: '0gpGqGHEr_8',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/0gpGqGHEr_8/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/0gpGqGHEr_8/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Favourite Colour (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 210,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'qvApKIuJ68M',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/qvApKIuJ68M/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/qvApKIuJ68M/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Never Get to Hold You (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 254,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'z7Zmc838tCE',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/z7Zmc838tCE/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/z7Zmc838tCE/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Love Again (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 217,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'ucshSaH5Jv4',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/ucshSaH5Jv4/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/ucshSaH5Jv4/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title:
        'Carly Rae Jepsen - I Really Like You (Liam Keegan Remix Radio Edit) (Audio)',
      description:
        'Album: E•MO•TION\nRelease date: August 21, 2015\nBuy E•MO•TION on iTunes: http://smarturl.it/E-MO-TION',
      duration: 189,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      projection: 'rectangular'
    },
    {
      videoId: 'n5g_xj0FWyw',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/n5g_xj0FWyw/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/n5g_xj0FWyw/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - First Time (Audio)',
      description: 'Album: EMOTION REMIXED +\nRelease date: March 18, 2016',
      duration: 216,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      regionRestriction: {
        blocked: [
          'VE',
          'ES',
          'ER',
          'ET',
          'VC',
          'VN',
          'VI',
          'SV',
          'VU',
          'EC',
          'VG',
          'EE',
          'EG',
          'EH',
          'VA',
          'MH',
          'MK',
          'MM',
          'ML',
          'MO',
          'MN',
          'MA',
          'MC',
          'ME',
          'MD',
          'MG',
          'MF',
          'MY',
          'MX',
          'MZ',
          'IT',
          'MQ',
          'MP',
          'MS',
          'MR',
          'MU',
          'MT',
          'MW',
          'MV',
          'WF',
          'FR',
          'IQ',
          'WS',
          'SB',
          'FM',
          'FO',
          'FI',
          'FJ',
          'FK',
          'NL',
          'IM',
          'NO',
          'NI',
          'IL',
          'NE',
          'NF',
          'NG',
          'NA',
          'NC',
          'NZ',
          'NU',
          'NP',
          'NR',
          'CK',
          'CI',
          'CH',
          'CO',
          'CN',
          'CM',
          'CL',
          'CC',
          'CG',
          'CF',
          'CD',
          'CZ',
          'CY',
          'CX',
          'CR',
          'JO',
          'CW',
          'CV',
          'CU',
          'SZ',
          'SY',
          'SX',
          'KG',
          'KE',
          'SS',
          'SR',
          'KI',
          'KH',
          'KN',
          'KM',
          'ST',
          'SK',
          'KR',
          'SI',
          'SH',
          'KW',
          'SN',
          'SM',
          'SL',
          'SC',
          'KZ',
          'SA',
          'SG',
          'SE',
          'SD',
          'UA',
          'DO',
          'DM',
          'DJ',
          'DK',
          'UG',
          'DE',
          'UM',
          'US',
          'DZ',
          'UY',
          'UZ',
          'SJ',
          'IO',
          'TZ',
          'LC',
          'LA',
          'TV',
          'TW',
          'TT',
          'TR',
          'LK',
          'LI',
          'LV',
          'TO',
          'LT',
          'LU',
          'LR',
          'LS',
          'TH',
          'TF',
          'TG',
          'TD',
          'TC',
          'LY',
          'AE',
          'AD',
          'AG',
          'AF',
          'LB',
          'ZW',
          'AM',
          'AL',
          'AO',
          'AI',
          'IS',
          'IR',
          'AU',
          'AT',
          'AW',
          'IN',
          'AQ',
          'AS',
          'AR',
          'IE',
          'ID',
          'AX',
          'AZ',
          'QA',
          'RU',
          'BH',
          'BI',
          'BJ',
          'ZM',
          'BM',
          'BN',
          'BO',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BY',
          'BZ',
          'KP',
          'BQ',
          'BR',
          'BS',
          'BT',
          'BV',
          'BW',
          'SO',
          'YE',
          'JE',
          'RS',
          'JM',
          'RW',
          'JP',
          'RO',
          'RE',
          'GW',
          'GU',
          'GT',
          'GS',
          'GR',
          'GQ',
          'GP',
          'GY',
          'GG',
          'GF',
          'GE',
          'GD',
          'GB',
          'KY',
          'GN',
          'GM',
          'GL',
          'GI',
          'GH',
          'TN',
          'OM',
          'TL',
          'TM',
          'TJ',
          'TK',
          'GA',
          'HR',
          'HT',
          'HU',
          'HK',
          'HN',
          'HM',
          'YT',
          'ZA',
          'PR',
          'PS',
          'PW',
          'PT',
          'PN',
          'PY',
          'PA',
          'PF',
          'PG',
          'PE',
          'PK',
          'PH',
          'BL',
          'PL',
          'PM'
        ]
      },
      projection: 'rectangular'
    },
    {
      videoId: 'Ao-HiX7w9GQ',
      thumbnail: {
        url: 'https://i.ytimg.com/vi/Ao-HiX7w9GQ/default.jpg',
        width: 120,
        height: 90
      },
      posterImage: 'https://i.ytimg.com/vi/Ao-HiX7w9GQ/hqdefault.jpg',
      channelId: 'UC-1rVsh8pvXBAMZ5q_B3CEg',
      channelTitle: 'Full Album!',
      title: 'Carly Rae Jepsen - Fever (Audio)',
      description: 'Album: EMOTION REMIXED +\nRelease date: March 18, 2016',
      duration: 184,
      dimension: '2d',
      definition: 'hd',
      caption: 'false',
      licensedContent: false,
      regionRestriction: {
        blocked: [
          'VE',
          'ES',
          'ER',
          'ET',
          'VC',
          'VN',
          'VI',
          'SV',
          'VU',
          'EC',
          'VG',
          'EE',
          'EG',
          'EH',
          'VA',
          'MH',
          'MK',
          'MM',
          'ML',
          'MO',
          'MN',
          'MA',
          'MC',
          'ME',
          'MD',
          'MG',
          'MF',
          'MY',
          'MX',
          'MZ',
          'IT',
          'MQ',
          'MP',
          'MS',
          'MR',
          'MU',
          'MT',
          'MW',
          'MV',
          'WF',
          'FR',
          'IQ',
          'WS',
          'SB',
          'FM',
          'FO',
          'FI',
          'FJ',
          'FK',
          'NL',
          'IM',
          'NO',
          'NI',
          'IL',
          'NE',
          'NF',
          'NG',
          'NA',
          'NC',
          'NZ',
          'NU',
          'NP',
          'NR',
          'CK',
          'CI',
          'CH',
          'CO',
          'CN',
          'CM',
          'CL',
          'CC',
          'CG',
          'CF',
          'CD',
          'CZ',
          'CY',
          'CX',
          'CR',
          'JO',
          'CW',
          'CV',
          'CU',
          'SZ',
          'SY',
          'SX',
          'KG',
          'KE',
          'SS',
          'SR',
          'KI',
          'KH',
          'KN',
          'KM',
          'ST',
          'SK',
          'KR',
          'SI',
          'SH',
          'KW',
          'SN',
          'SM',
          'SL',
          'SC',
          'KZ',
          'SA',
          'SG',
          'SE',
          'SD',
          'UA',
          'DO',
          'DM',
          'DJ',
          'DK',
          'UG',
          'DE',
          'UM',
          'US',
          'DZ',
          'UY',
          'UZ',
          'SJ',
          'IO',
          'TZ',
          'LC',
          'LA',
          'TV',
          'TW',
          'TT',
          'TR',
          'LK',
          'LI',
          'LV',
          'TO',
          'LT',
          'LU',
          'LR',
          'LS',
          'TH',
          'TF',
          'TG',
          'TD',
          'TC',
          'LY',
          'AE',
          'AD',
          'AG',
          'AF',
          'LB',
          'ZW',
          'AM',
          'AL',
          'AO',
          'AI',
          'IS',
          'IR',
          'AU',
          'AT',
          'AW',
          'IN',
          'AQ',
          'AS',
          'AR',
          'IE',
          'ID',
          'AX',
          'AZ',
          'QA',
          'RU',
          'BH',
          'BI',
          'BJ',
          'ZM',
          'BM',
          'BN',
          'BO',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BY',
          'BZ',
          'KP',
          'BQ',
          'BR',
          'BS',
          'BT',
          'BV',
          'BW',
          'SO',
          'YE',
          'JE',
          'RS',
          'JM',
          'RW',
          'JP',
          'RO',
          'RE',
          'GW',
          'GU',
          'GT',
          'GS',
          'GR',
          'GQ',
          'GP',
          'GY',
          'GG',
          'GF',
          'GE',
          'GD',
          'GB',
          'KY',
          'GN',
          'GM',
          'GL',
          'GI',
          'GH',
          'TN',
          'OM',
          'TL',
          'TM',
          'TJ',
          'TK',
          'GA',
          'HR',
          'HT',
          'HU',
          'HK',
          'HN',
          'HM',
          'YT',
          'ZA',
          'PR',
          'PS',
          'PW',
          'PT',
          'PN',
          'PY',
          'PA',
          'PF',
          'PG',
          'PE',
          'PK',
          'PH',
          'BL',
          'PL',
          'PM'
        ]
      },
      projection: 'rectangular'
    }
  ]
};

export default initialPlaylist;
